# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-02 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympian',
            name='age',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='olympian',
            name='height',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='olympian',
            name='weight',
            field=models.CharField(max_length=255),
        ),
    ]
