# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-03 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympians', '0003_olympian_medal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympian',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='olympian',
            name='updated_at',
        ),
    ]
